"""
SEISF (DLT) decode path for utig/vkg.1 .. vkg.46.

Background
----------
* DLT labels on UTIG 8-mm cassettes are SEISF: raw lander bit strings with
  spacecraft DRAM address scrambling, as stored at JPL / MIT / Galveston.
* VUS labels (vkg.47-56) are USEIS: the *same* science after N51VUS (PDP-15)
  removed pads, ran MAP/UNSCR, and rewrote frames as 450-byte blocks.

Hardware scramble (PD7400072) + ground inverse (N51SUB):
  The 2048-bit seismometer buffer is read out to the DAPU in an order that
  depends on pointer Q vs 503 (four 512-bit pages; lengths Q+9 and 503-Q).
  N51SUB probes Q via the MAP table (matv) from the first scrambled data pair,
  then SEISDT/UNSCR recomposes sequential buffer bits.

This module:
  1. Walks SEISF cassette structure (1000-byte headers, 10752/10764 records).
  2. Finds 672-byte logical frames (224 halfwords) with SEISF engineering headers.
  3. Exports the 108-byte shared SEISF/VUS header (year, DOY, …).
  4. Unscrambles science via PD7400072 Q-page reordering (with matv/Q scan),
     then hands off to vus_decode for GCSC / mode / amplitudes.

Status (2026-08):
  - Header + PD7400072 Q-page reorder solid.
  - Science Path D (primary): halfword pairs → 36 bits, drop top 4
    (hi[0:4]) keep hi[4:18]||lo[0:18] = 32 bits/pair (BLP-style 32 of 36);
    **Q = matv** (N51SUB NBA/NBB with Q=matv); **bit_offset = 15**.
  - vkg.1↔vkg.47 matched frames: **2048/2048 + full frame equality** with
    next-record halfword lookahead for record-boundary frames.
  - Earlier Q=matv−2 / off=13 left ≤8 page-edge residuals (off-by-two of
    the same pairing). Structural N51SUB BOUT still open as Path E.
  - Frame-header discovery: the header word-1 gate accepts 0o000/0o100/0o200
    (not only 0o100); see _VALID_HI_WORDS. Recovers ~23% more header-matched
    pairs on vkg.1 subgroup 0 (380→423) with no change to bit-exact results.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterator, List, Optional, Sequence, Tuple

from vkg_format import (
    BYTES_PER_FRAME_VUS,
    SEISF_BYTES_PER_FRAME,
    SEISF_FIRST_FRAME_HALFWORDS_OFFSET,
    SEISF_HALFWORDS_PER_FRAME,
    SEISF_HEADER_HALFWORDS,
    body_to_halfwords,
    halfwords_to_frame_bytes,
    open_vkg,
)
from vus_decode import DecodedFrame, decode_vus_frame, parse_seisf_header_fields

MASK18 = 0o777777

# Primary packing (Path D): 36-bit halfword pair → keep indices 4..35
# (drop top 4 of first halfword). Multi-frame: Q = matv, bit_offset = 15.
# (Q=matv−k with off=15−k is almost as good; k=0 is exact vs VUS.)
_PAIR36_DROP = (0, 1, 2, 3)
_PAIR36_BIT_OFFSET = 15
# Halfwords needed after frame_base for Path D (header + ~64 pairs + margin)
_PATH_D_HALFWORDS_SPAN = SEISF_HEADER_HALFWORDS + 64 * 2 + 8

# Legacy fallback: keep 16 of 18 halfword bits (per-halfword drop).
_DROP16_CANDIDATES = (
    tuple(i for i in range(18) if i not in (6, 7)),
    tuple(i for i in range(18) if i not in (14, 15)),
    tuple(i for i in range(18) if i not in (16, 17)),
)
_DROP16_KEEP = _DROP16_CANDIDATES[0]

# PDP-15 MAP BASE table (octal constants as written in N51SUB)
_MAP_BASE = [
    0o410604,
    0o712541,
    0o572334,
    0o424126,
    0o477311,
    0o133744,
    0o651460,
    0o061450,
    0o645772,
    0o130726,
    0o263617,
    0o564065,
    0o556602,
    0o657525,
    0o005127,
    0o456700,
    0o716447,
    0o535211,
    0o031605,
    0o733150,
    0o357037,
    0o740757,
    0o427144,
    0o045166,
    0o436371,
    0o542510,
    0o706653,
    0o423042,
    0,
]


def _lls(l: int, ac: int, mq: int, n: int) -> Tuple[int, int, int]:
    """LLS matching N51SUB test sheet / materials2 seisf/func.py (AC,MQ,L)."""
    val = ((ac & MASK18) << 19) | ((mq & MASK18) << 1) | (l & 1)
    val = (val << n) & ((1 << 37) - 1)
    l = val & 1
    mq = (val >> 1) & MASK18
    ac = (val >> 19) & MASK18
    return l, ac, mq


def _lrs(l: int, ac: int, mq: int, n: int) -> Tuple[int, int, int]:
    val = (l << 36) | ((ac & MASK18) << 18) | (mq & MASK18)
    val >>= n
    mq = val & MASK18
    ac = (val >> 18) & MASK18
    l = (val >> 36) & 1
    return l, ac, mq


def _ral(l: int, ac: int) -> Tuple[int, int]:
    nl = (ac >> 17) & 1
    ac = ((ac << 1) | (l & 1)) & MASK18
    return nl, ac


def build_map_table() -> list[int]:
    """512-slot MAT[] as generated by N51SUB MAP (values 1..511)."""
    mat = [0] * 512
    temp = 0
    q = -511
    for base_mq in _MAP_BASE:
        mq = base_mq
        for _ in range(18):
            _, temp, mq = _lls(0, temp & 0o777, mq, 1)
            temp &= 0o777
            mat[temp] = q + 512
            q += 1
            if q == 0:
                return mat
    return mat


_MAT = build_map_table()
_ADDR_OF_SEQ = [0] * 512
for _a, _s in enumerate(_MAT):
    if 1 <= _s <= 511:
        _ADDR_OF_SEQ[_s] = _a


@dataclass
class SeisfFrameLoc:
    subgroup: int
    record_index: int
    halfword_offset: int
    file_byte_hint: int  # absolute file offset when available


# Word1 (``hi``) of a real frame header is not the single fixed sync value
# 0o100 assumed from the gold frame alone: a corpus survey restricted to
# lo == 0o504 (the gold frame's word-2 value) plus a valid BCD year/DOY found
# hi in {0o000, 0o100, 0o200} occurring in the thousands on vkg.1/26/29,
# against a long tail of other hi values occurring at most 6 times each in a
# multi-million-halfword scan (consistent with rare BCD coincidences, not
# real headers). hi therefore looks like a small counter/flag shifted into
# the top bits (0, 1, 2 << 6) rather than a constant marker.
_VALID_HI_WORDS = (0, 0o100, 0o200)


def looks_like_seisf_frame_header(halfwords: Sequence[int], base: int) -> bool:
    """Heuristic for SEISF eng-format frame start (word1 high/low)."""
    if base + SEISF_HEADER_HALFWORDS > len(halfwords):
        return False
    hi, lo = halfwords[base], halfwords[base + 1]
    # Gold / typical: 000100 000504 (octal) — logical record marker.
    # See _VALID_HI_WORDS above: hi also legitimately takes 0o000 / 0o200.
    if hi not in _VALID_HI_WORDS:
        return False
    if not (0 < lo < 0o10000):
        return False
    # Validate BCD year / DOY fields via 108-byte header packing
    try:
        hdr = halfwords_to_frame_bytes(list(halfwords[base : base + SEISF_HEADER_HALFWORDS]))
        year, doy = parse_seisf_header_fields(hdr + bytes(342))
    except Exception:
        return False
    if year < 1976 or year > 1982:
        return False
    if doy < 1 or doy > 366:
        return False
    return True


def find_seisf_frame_bases(
    halfwords: Sequence[int],
    *,
    start_limit: Optional[int] = None,
) -> list[int]:
    """Return halfword indices of SEISF science frames in a halfword buffer.

    Scans **every** halfword offset with ``looks_like_seisf_frame_header``
    (dense discovery). Earlier production scans used pitch-224 preferred phase
    and returned as soon as any phase found a base; that skipped off-pitch
    headers coexisting with on-pitch ones and inflated VUS-only residuals
    (~39% of former VUS-only recovered by exhaustive harvest).

    ``start_limit`` (optional) restricts accepted *starts* to bases in
    ``[0, start_limit)`` so a caller can append following-record halfwords for
    header validation at the trailing edge without attributing those starts to
    the next physical record. Validation still uses the full extended buffer.
    """
    max_start = len(halfwords) - SEISF_HEADER_HALFWORDS
    if max_start < 0:
        return []
    if start_limit is not None:
        max_start = min(max_start, start_limit - 1)
    if max_start < 0:
        return []
    bases: list[int] = []
    for base in range(0, max_start + 1):
        if looks_like_seisf_frame_header(halfwords, base):
            bases.append(base)
    return bases


def seisf_frame_header_bytes(halfwords: Sequence[int], base: int) -> bytes:
    """108-byte SEISF/VUS-compatible header from 36 halfwords."""
    return halfwords_to_frame_bytes(list(halfwords[base : base + SEISF_HEADER_HALFWORDS]))


def _mat_probe(halfwords: Sequence[int], data_base: int) -> Tuple[int, int]:
    """Return (mat_value, mq_after_lls) from first data halfword pair."""
    ac = halfwords[data_base] & MASK18
    mq = halfwords[data_base + 1] & MASK18
    _, ac, mq = _lls(0, ac, mq, 1)
    temp = ac & 0o777
    return _MAT[temp], mq


def _unscr_bits_from_ea(
    halfwords: Sequence[int],
    ea: int,
    nbits: int,
    cxr: int,
    mq_init: int,
) -> list[int]:
    """
    Portable reconstruction of N51SUB UNSCR bit walk.

    Address path matches the N51SUB test sheet for TAD/LRS/RAL/CXR/LLS.
    Bits are then taken MSB-first from the 36-bit AC||MQ window at XR,
    refilling from successive halfwords (BLP-style advance).
    """
    l = 0
    ac = ea & MASK18
    mq = mq_init & MASK18
    ac = (ac + 0o1117) & MASK18
    l = 0
    l, ac, mq = _lrs(l, ac, mq, 5)
    l, ac = _ral(l, ac)
    ac = (ac + (cxr & MASK18)) & MASK18
    xr = ac % len(halfwords)
    l, bit_param, mq = _lls(l, 0, mq, 5)
    skip = bit_param & 0x3F

    # Load pair at XR
    ac = halfwords[xr] & MASK18
    mq = halfwords[(xr + 1) % len(halfwords)] & MASK18
    l = 0
    # Align by LRS skip (clamp)
    if skip:
        l, ac, mq = _lrs(l, ac, mq, min(skip, 35))

    bits: list[int] = []
    shifts_since_load = 0
    hw_ptr = (xr + 2) % len(halfwords)
    while len(bits) < nbits:
        bit = (ac >> 17) & 1
        bits.append(bit)
        # LLS 1 on (AC,MQ)
        l, ac, mq = _lls(l, ac, mq, 1)
        shifts_since_load += 1
        if shifts_since_load >= 36:
            # BLP: next source pair
            ac = halfwords[hw_ptr] & MASK18
            mq = halfwords[(hw_ptr + 1) % len(halfwords)] & MASK18
            hw_ptr = (hw_ptr + 2) % len(halfwords)
            shifts_since_load = 0
            # LRS 16 style realign sometimes used after AXR 2
            if nbits - len(bits) > 18:
                l, ac, mq = _lrs(0, ac, mq, 16)
    return bits


def _halfwords_to_mbs_data_bits(halfwords_150: Sequence[int]) -> list[int]:
    """
    Pack 150 halfwords (75 words) the VUS way and return the 2048-bit data
    region (make_bit_stream indices 648 .. 648+2047).
    """
    frame = halfwords_to_frame_bytes(list(halfwords_150)[:150])
    if len(frame) < BYTES_PER_FRAME_VUS:
        frame = frame + bytes(BYTES_PER_FRAME_VUS - len(frame))
    from vus_decode import make_bit_stream

    return make_bit_stream(frame[:BYTES_PER_FRAME_VUS])[648 : 648 + 2048]


def _scramble_bits_via_map(scrambled: Sequence[int], inverse: bool = False) -> list[int]:
    """
    Apply N51SUB MAP as a 4-bit-cell permutation on a 2048-bit string.

    Spacecraft DRAM is 512 cells × 4 bits. MAP[address] = sequential index.
    Write direction: sequential cell k is stored at address ADDR_OF_SEQ[k+1].
    inverse=False  : DESCRAMBLE (read sequential from scrambled address)
    inverse=True   : SCRAMBLE (write sequential into mapped addresses)
    """
    src = list(scrambled[:2048])
    if len(src) < 2048:
        src.extend([0] * (2048 - len(src)))
    out = [0] * 2048
    for seq in range(512):
        # sequential cell index 0..511
        addr = _ADDR_OF_SEQ[seq + 1] if seq + 1 <= 511 else seq
        if inverse:
            # store sequential cell `seq` into address `addr`
            for b in range(4):
                out[addr * 4 + b] = src[seq * 4 + b]
        else:
            # emit sequential cell `seq` from address `addr`
            for b in range(4):
                out[seq * 4 + b] = src[addr * 4 + b]
    return out


def _halfwords_data_msb_stream(
    halfwords: Sequence[int],
    frame_base: int,
    *,
    keep_bits: Optional[Sequence[int]] = None,
    bit_offset: int = 0,
) -> list[int]:
    """
    Pack science halfwords after the 36-halfword header into a bit stream.

    keep_bits: which of the 18 halfword bits (0=MSB .. 17=LSB) to keep, in
      that order. Default = all 18. Legacy Path-D fallback uses _DROP16_KEEP.
    bit_offset: skip this many leading kept bits before taking 2048.
    """
    data_base = frame_base + SEISF_HEADER_HALFWORDS
    if keep_bits is None:
        keep_bits = tuple(range(18))
    packed: list[int] = []
    # enough halfwords for 2048 bits even with 16-bit packing + offset
    n_hw = 114 + 4
    for i in range(n_hw):
        if data_base + i >= len(halfwords):
            break
        h = halfwords[data_base + i] & MASK18
        for b in keep_bits:
            packed.append((h >> (17 - b)) & 1)
    if bit_offset:
        packed = packed[bit_offset:]
    if len(packed) < 2048:
        packed.extend([0] * (2048 - len(packed)))
    return packed[:2048]


def _halfwords_pair36_stream(
    halfwords: Sequence[int],
    frame_base: int,
    *,
    drop_bits: Sequence[int] = _PAIR36_DROP,
    bit_offset: int = _PAIR36_BIT_OFFSET,
) -> list[int]:
    """
    Pack science as consecutive halfword pairs (36 MSB-first bits each),
    drop selected pair bit indices, then apply bit_offset and truncate to 2048.

    Default drop_bits=(0,1,2,3) keeps hi[4:18]||lo[0:18] = 32 bits/pair.
    Matches multi-frame vkg.1↔vkg.47 with Q=matv and bit_offset=15.
    """
    data_base = frame_base + SEISF_HEADER_HALFWORDS
    keep = tuple(i for i in range(36) if i not in set(drop_bits))
    packed: list[int] = []
    # 64 pairs × 32 bits + margin for bit_offset
    i = 0
    while data_base + i + 1 < len(halfwords) and len(packed) < 2048 + bit_offset + 32:
        hi = halfwords[data_base + i] & MASK18
        lo = halfwords[data_base + i + 1] & MASK18
        pair = [(hi >> (17 - bi)) & 1 for bi in range(18)] + [
            (lo >> (17 - bi)) & 1 for bi in range(18)
        ]
        for k in keep:
            packed.append(pair[k])
        i += 2
    if bit_offset:
        packed = packed[bit_offset:]
    if len(packed) < 2048:
        packed.extend([0] * (2048 - len(packed)))
    return packed[:2048]


def _n51_unscr_segment(
    halfwords: Sequence[int],
    ea: int,
    nbits: int,
    cxr: int,
    mq_init: int = 0,
) -> list[int]:
    """
    N51SUB UNSCR+BOUT bit walk for one (EA, nbits) segment.

    Implements the address setup (TAD 1117 / LRS 5 / RAL / +CXR / LLS 5 /
    TCA / AAC 15 / SPA→BB) and serial extract via LLS1+RAR, with BLP-style
    refill (AXR 2, LRS 16, 18-then-14 bit groups). Group sizes for the BB
    first extract use residual low bits (bp & 037); AA path uses (AAC15 & 017).

    This is the structural N51 walk. Gold-frame bit agreement is still below
    Path D (16-bit drop) for amplitudes; kept as a scored candidate.
    """
    if nbits <= 0:
        return []
    l = 0
    ac = ea & MASK18
    mq = mq_init & MASK18
    ac = (ac + 0o1117) & MASK18
    l = 0
    l, ac, mq = _lrs(l, ac, mq, 5)
    l, ac = _ral(l, ac)
    ac = (ac + (cxr & MASK18)) & MASK18
    xr = ac
    ac = 0
    l, bit_param, mq = _lls(l, ac, mq, 5)
    bp = bit_param & MASK18
    ac = (-bp) & MASK18
    ac = (ac + 0o15) & MASK18
    sign = (ac >> 17) & 1  # SPD AC0; 1 → BB branch

    def take() -> int:
        """BOUT bit: LLS 1 (Link unchanged) then RAR → Link holds extracted bit."""
        nonlocal l, ac, mq
        # Hardware LLS: MQ0 → AC17(LSB); AC0(MSB) lost; Link unchanged.
        ac = ((ac << 1) | ((mq >> 17) & 1)) & MASK18
        mq = (mq << 1) & MASK18
        # RAR: Link ← AC17 (new bit), AC ← (Link_old≪17)|(AC≫1)
        new_l = ac & 1
        ac = (((l & 1) << 17) | ((ac >> 1) & 0o377777)) & MASK18
        l = new_l
        return new_l

    # align load
    if sign == 0:
        first_ns = ac & 0o17
        if first_ns == 0:
            first_ns = 1
        ac = halfwords[xr % len(halfwords)] & MASK18
        l, ac, mq = _lrs(0, ac, mq, min(1 + first_ns, 35))
        xr_cur = xr
    else:
        first_ns = bp & 0o37
        if first_ns == 0:
            first_ns = 18
        ac = halfwords[(xr + 1) % len(halfwords)] & MASK18
        l, ac, mq = _lrs(0, ac, mq, 19)  # (LRS 23) ≈ 19 decimal
        xr_cur = xr

    bits: list[int] = []
    for _ in range(min(first_ns, nbits)):
        bits.append(take())

    group = 18
    while len(bits) < nbits:
        for _ in range(group):
            if len(bits) >= nbits:
                break
            bits.append(take())
        if len(bits) >= nbits:
            break
        xr_cur = (xr_cur + 2) % len(halfwords)
        ac = halfwords[xr_cur] & MASK18
        l, ac, mq = _lrs(0, ac, mq, 16)
        group = 14
    return bits[:nbits]


def n51_unscramble_2048(halfwords: Sequence[int], frame_base: int) -> list[int]:
    """Full CLP: 4 pages × (NBA@EA + NBB@EB) using matv from word19."""
    data_base = frame_base + SEISF_HEADER_HALFWORDS
    if data_base + 1 >= len(halfwords):
        return [0] * 2048
    matv, mq_saved = _mat_probe(halfwords, data_base)
    if matv <= 0:
        matv = 503
    if matv >= 503:
        # QEQ503: single UNSCR of 2048 bits from EA=0
        return _n51_unscr_segment(halfwords, 0, 2048, frame_base, mq_saved)[:2048]

    ea0 = 503 - matv
    nba = matv + 9
    nbb = 503 - matv
    out: list[int] = []
    for page in range(4):
        out.extend(
            _n51_unscr_segment(
                halfwords, ea0 + page * 512, nba, frame_base, mq_saved
            )
        )
        out.extend(
            _n51_unscr_segment(
                halfwords, page * 512, nbb, frame_base, mq_saved
            )
        )
    if len(out) < 2048:
        out.extend([0] * (2048 - len(out)))
    return out[:2048]


def pd7400072_readout_order(q: int) -> list[int]:
    """
    DAPU readout order (PD7400072 Section 3.1.1.5.4.4.2), as 0-based buffer indices.

    Source (FromSD-37D000&PD7400072.pdf, sheet 19, "Sequence of Read-Out From
    the Buffer"), 1-indexed buffer bit numbers, per page base B = k*512
    (k = 0..3):

      Q < 503:  bit(Q+10+B) .. bit(512+B), then bit(1+B) .. bit(Q+9+B)
      Q > 503:  bit(Q-502+B) .. bit(512+B), then bit(1+B) .. bit(Q-503+B)
      Q == 503: bit(1) .. bit(2048)  (identity)

    Q is the 9-bit DAPU buffer pointer (0-503 for the "less than" case;
    504-511 for the "greater than" case per the 9-bit field range), read
    directly from the data as `matv` (Q == matv, validated for 0 < Q < 503
    against 366 header-matched SEISF/VUS pairs; the same Q == matv mapping is
    used here for Q > 503, since matv is the raw probed hardware pointer in
    both regimes).
    """
    if q == 503:
        return list(range(2048))
    order: list[int] = []
    if q < 503:
        q = max(0, min(502, q))
        for k in range(4):
            b = k * 512
            # high part of page then low part (matches PDF + N51SUB NBA/NBB sizes)
            order.extend(range(q + 10 + b - 1, (k + 1) * 512))
            order.extend(range(b, q + 9 + b))
    else:
        q = max(504, min(511, q))
        for k in range(4):
            b = k * 512
            order.extend(range(q - 502 + b - 1, b + 512))
            order.extend(range(b, q - 503 + b))
    return order


def pd7400072_unscramble(stream_bits: Sequence[int], q: int) -> list[int]:
    """Invert DAPU readout: sequential buffer[i] from scrambled stream order."""
    order = pd7400072_readout_order(q)
    buf = [0] * 2048
    src = list(stream_bits[:2048])
    if len(src) < 2048:
        src.extend([0] * (2048 - len(src)))
    for i, dst in enumerate(order):
        buf[dst] = src[i] & 1
    return buf


def _addr_residual(ea: int, cxr: int) -> int:
    """N51SUB UNSCR residual after TAD 1117 / LRS 5 / RAL / +CXR / LLS 5."""
    ac = (ea + 0o1117) & MASK18
    l, ac, mq = _lrs(0, ac, 0, 5)
    l, ac = _ral(l, ac)
    ac = (ac + (cxr & MASK18)) & MASK18
    _, bit_param, _ = _lls(l, 0, mq, 5)
    return bit_param & MASK18


def estimate_q_from_matv(halfwords: Sequence[int], frame_base: int) -> Tuple[int, int]:
    """
    Estimate DAPU Q and matv for a SEISF frame.

    N51SUB (photographed listing) uses NBA=matv+9 and NBB=503-matv, which
    are exactly PD7400072 lengths for **Q = matv**. Path D (pair36 packing)
    matches VUS bit-for-bit with this Q and bit_offset=15.

    Returns (q_primary, matv) where q_primary = matv for all matv in
    [1, 511] (Q == matv throughout: validated for 0 < matv < 503 against
    366 header-matched pairs; matv == 503 is the PD7400072 identity case;
    504 <= matv <= 511 uses the PD7400072 "Q > 503" formula -- see
    `pd7400072_readout_order`).
    """
    data_base = frame_base + SEISF_HEADER_HALFWORDS
    if data_base + 1 >= len(halfwords):
        return 0, 503
    matv, _ = _mat_probe(halfwords, data_base)
    if matv <= 0:
        matv = 503
    if matv > 511:
        matv = 511
    return matv, matv


def estimate_q18_from_matv(halfwords: Sequence[int], frame_base: int) -> Tuple[int, int]:
    """Q for 18-bit packing: matv − residual (gold ≈ matv-31 = 392)."""
    data_base = frame_base + SEISF_HEADER_HALFWORDS
    if data_base + 1 >= len(halfwords):
        return 0, 503
    matv, _ = _mat_probe(halfwords, data_base)
    if matv <= 0:
        matv = 503
    if matv >= 503:
        return 502 if matv > 503 else 503, matv
    ea = 503 - matv
    bp = _addr_residual(ea, frame_base)
    q = matv - bp if matv >= bp else matv
    return max(0, min(502, q)), matv


def _score_science_bits(bits: Sequence[int]) -> int:
    """Heuristic quality of a candidate 2048-bit instrument buffer."""
    from vus_decode import get_int_from_bit_stream

    b = list(bits[:2048])
    if len(b) < 2048:
        b.extend([0] * (2048 - len(b)))
    gcsc = get_int_from_bit_stream(b, 0, 23) << 1
    mode = get_int_from_bit_stream_local(b, 23, 2)
    score = 0
    # VL2 GCSC after landing is ~1e5–few e5 (seconds-scale); later sols higher but
    # seldom near full 24-bit range on early SEISF reels we care about.
    if 50_000 <= gcsc <= 2_000_000:
        score += 55
    elif 1_000 <= gcsc < (1 << 24) and gcsc not in (0, 0xFFFFFF):
        score += 15
    if mode in (0, 1, 2, 3):
        score += 10
    w = sum(b)
    if 50 < w < 2000:
        score += 5
    if sum(b[23:53]) > 0:
        score += 3
    return score


def map_unscramble_data_bits(
    halfwords: Sequence[int], frame_base: int
) -> list[int]:
    """
    Unscramble the 2048-bit science buffer of one SEISF frame into VUS bit
    order expected by make_bit_stream data region (offset 648).

    Candidates (best by _score_science_bits wins):
      A — 18-bit MSB stream + PD7400072 Q (from matv − residual)
      B — Legacy address walk (_unscr_bits_from_ea)
      C — MAP 4-bit cell permute (ruled out as stacked layer; low bonus)
      D — pair36 drop top-4 + Q=matv + off=15 (primary; 2048/2048 vs VUS)
      D'— legacy 16-of-18 keep fallback
      E — N51SUB CLP/UNSCR/BOUT structural walk (n51_unscramble_2048)
    """
    from vus_decode import get_int_from_bit_stream

    stream = _halfwords_data_msb_stream(halfwords, frame_base)
    q_matv, matv = estimate_q_from_matv(halfwords, frame_base)
    q18, _ = estimate_q18_from_matv(halfwords, frame_base)

    candidates: list[tuple[list[int], int]] = []

    def _add(buf: list[int], bonus: int = 0) -> None:
        candidates.append((list(buf[:2048]), bonus))
        flipped = list(buf[:2048])
        if flipped:
            flipped[0] ^= 1
            candidates.append((flipped, bonus - 30))  # flip rarely needed for pair36

    # --- Path D primary: pair36 drop(0..3), Q=matv, off=15 ---
    # Covers the full valid matv range [1, 511] returned by estimate_q_from_matv:
    # Q<503 (validated), Q==503 (identity), and Q in [504,511] (PD7400072
    # "Q>503" formula). In practice matv is always in this range once the
    # probe succeeds, so this branch is now the only one taken; the scored
    # fallback ensemble below is retained as a defensive dead path.
    if 0 < matv <= 511:
        s_primary = _halfwords_pair36_stream(
            halfwords,
            frame_base,
            drop_bits=_PAIR36_DROP,
            bit_offset=_PAIR36_BIT_OFFSET,
        )
        return pd7400072_unscramble(s_primary, q_matv)

    # matv out of range: scored fallbacks (18-bit Q residual, MAP, N51 BOUT)
    # --- Path A: 18-bit PD7400072 (Q18 = matv − residual ≈ matv-31) ---
    q_list: list[int] = [q18]
    if 0 < matv < 503:
        q_list.extend(
            [
                max(0, matv - 31),
                max(0, matv - 27),
                max(0, matv - 13),
                max(0, matv - 9),
                max(0, matv - 2),
                matv if matv < 503 else 502,
            ]
        )
    for dq in (-1, 1, -2, 2):
        q_list.append(max(0, min(502, q18 + dq)))

    def q_bonus(q: int) -> int:
        if q == q18:
            return 15
        if abs(q - q18) <= 2:
            return 4
        return 0

    seen_q: set[int] = set()
    for q in q_list:
        if q in seen_q or not (0 <= q <= 503):
            continue
        seen_q.add(q)
        buf = list(stream) if q == 503 else pd7400072_unscramble(stream, q)
        _add(buf, q_bonus(q))

    def _has_plausible_gcsc(c: list[int]) -> bool:
        g = get_int_from_bit_stream(c, 0, 23) << 1
        return 50_000 <= g <= 2_000_000

    primary_ok = any(
        _has_plausible_gcsc(c) for c, b in candidates if b >= 100
    )
    if not primary_ok and 0 < matv < 503:
        for k in range(0, 40):
            q = max(0, matv - k)
            if q in seen_q:
                continue
            seen_q.add(q)
            _add(pd7400072_unscramble(stream, q), 5)

    # --- Path B: legacy EA walk ---
    data_base = frame_base + SEISF_HEADER_HALFWORDS
    if data_base + 2 < len(halfwords):
        matv_b, mq_saved = _mat_probe(halfwords, data_base)
        if matv_b == 0:
            matv_b = 503
        if matv_b == 503:
            segments = [(0, 2048)]
        elif matv_b > 503:
            segments = [(page * 512, 512) for page in range(4)]
        else:
            ea = 503 - matv_b
            nba = matv_b + 9
            nbb = 503 - matv_b
            segments = []
            for page in range(4):
                segments.append((ea + page * 512, nba))
                segments.append((page * 512, nbb))
        bits_b: list[int] = []
        for ea, nbits in segments:
            if nbits <= 0:
                continue
            bits_b.extend(
                _unscr_bits_from_ea(halfwords, ea, nbits, frame_base, mq_saved)
            )
        bits_b = bits_b[:2048]
        if len(bits_b) < 2048:
            bits_b.extend([0] * (2048 - len(bits_b)))
        candidates.append((bits_b, 0))

    # --- Path C: MAP cell (low weight; known dead end as stacked layer) ---
    h150 = list(halfwords[frame_base : frame_base + 150])
    if len(h150) < 150:
        h150.extend([0] * (150 - len(h150)))
    packed = _halfwords_to_mbs_data_bits(h150)
    for c in (
        _scramble_bits_via_map(packed, inverse=False),
        _scramble_bits_via_map(packed, inverse=True),
        packed,
    ):
        candidates.append((c, 0))

    # --- Path E: structural N51SUB CLP/BOUT ---
    try:
        bout = n51_unscramble_2048(halfwords, frame_base)
        _add(bout, 5)
    except Exception:
        pass

    if not candidates:
        return [0] * 2048

    best = candidates[0][0]
    best_score = -1
    for c, bonus in candidates:
        if len(c) < 2048:
            c = list(c) + [0] * (2048 - len(c))
        score = _score_science_bits(c) + bonus
        gcsc = get_int_from_bit_stream(list(c), 0, 23) << 1
        if 50_000 <= gcsc <= 2_000_000:
            score += 20
        if sum(c[23:45]) >= 4:
            score += 2
        # Sample-byte sanity (catches the classic nibble-stuck [15,240,240] failure
        # of 18-bit packing when 16-bit keep would recover plausible bytes).
        s0 = get_int_from_bit_stream(c, 53, 8)
        s1 = get_int_from_bit_stream(c, 61, 8)
        s2 = get_int_from_bit_stream(c, 69, 8)
        if (s0, s1) in ((15, 240), (240, 15), (15, 15), (240, 240)):
            score -= 35
        # Prefer diverse leading sample triple over mono/stuck patterns
        if len({s0, s1, s2}) >= 2:
            score += 5
        # Soft check via full VUS parse (mode/sample count only — no amplitude GT)
        try:
            hdr = seisf_frame_header_bytes(halfwords, frame_base)
            fr = _inject_data_bits_into_vus_frame(hdr, c)
            dec = decode_vus_frame(fr, 0)
            if dec and dec.blocks:
                bl = dec.blocks[0]
                if bl.cs.mode in (0, 1, 2, 3):
                    score += 8
                if 20 <= bl.ndata <= 90:
                    score += 12
                # Event/normal with non-trivial first Z amp is common on lander
                if bl.amp and bl.amp[0] and any(abs(x) > 3 for x in bl.amp[0][:5]):
                    score += 6
        except Exception:
            pass
        if score > best_score:
            best_score = score
            best = c
    return best


def get_int_from_bit_stream_local(bits: Sequence[int], offset: int, length: int) -> int:
    ret = 0
    for i in range(length):
        ret = (ret << 1) | (bits[offset + length - 1 - i] & 1)
    return ret


def _inject_data_bits_into_vus_frame(header_108: bytes, data_bits: Sequence[int]) -> bytes:
    """
    Build a synthetic 450-byte VUS frame whose make_bit_stream data region
    equals data_bits[0:2048], keeping the original SEISF/VUS header bytes.
    """
    frame = bytearray(header_108[:108]) + bytearray(BYTES_PER_FRAME_VUS - 108)
    target = list(data_bits[:2048])
    if len(target) < 2048:
        target.extend([0] * (2048 - len(target)))
    for word in range(19, 76):
        for i in range(36):
            stream_offset = (word - 1) * 36 + ((17 - i) if i < 18 else (35 - i + 18))
            if stream_offset < 18 * 36:
                continue
            data_off = stream_offset - 18 * 36
            if data_off >= 2048:
                continue
            bit = target[data_off] & 1
            p = (word - 1) * 6
            bo = i // 6
            bi = i % 6
            shift = 5 - bi
            frame[p + bo] = (frame[p + bo] & ~(1 << shift) & 0x3F) | (bit << shift)
    return bytes(frame)


def seisf_frame_to_vus_bytes(halfwords: Sequence[int], frame_base: int) -> bytes:
    """Unscramble one SEISF frame into a 450-byte VUS-like frame."""
    header = seisf_frame_header_bytes(halfwords, frame_base)
    data_bits = map_unscramble_data_bits(halfwords, frame_base)
    return _inject_data_bits_into_vus_frame(header, data_bits)


def seisf_frame_raw_as_vus_guess(halfwords: Sequence[int], frame_base: int) -> bytes:
    """
    Assemble VUS-sized frame *without* MAP: take first 75 36-bit words of the
    SEISF frame payload (header + leading scrambled data words). Useful for
    structure/debug; GCSC/amplitudes will usually be wrong.
    """
    # 75 words = 150 halfwords
    chunk = list(halfwords[frame_base : frame_base + 150])
    if len(chunk) < 150:
        chunk.extend([0] * (150 - len(chunk)))
    return halfwords_to_frame_bytes(chunk)


def halfwords_span_for_frame(frame_base: int) -> int:
    """Absolute halfword index exclusive-end needed to unscramble frame_base."""
    return frame_base + _PATH_D_HALFWORDS_SPAN


def extend_halfwords_across_records(
    records: Sequence[Sequence[int]],
    record_index: int,
    need_len: int,
) -> list[int]:
    """
    Build a halfword array starting at records[record_index], appending
    subsequent physical records until len >= need_len (or body ends).

    SEISF science frames near the end of a 10752-byte record can spill into
    the next record; pair36 packing needs ~168 halfwords past the header start.
    """
    if record_index < 0 or record_index >= len(records):
        return []
    out = list(records[record_index])
    ri = record_index + 1
    while len(out) < need_len and ri < len(records):
        out.extend(records[ri])
        ri += 1
    return out


def iter_seisf_frames(
    path: str,
) -> Iterator[Tuple[SeisfFrameLoc, List[int], bytes]]:
    """
    Yield (location, halfword_view, frame_header_bytes) for each SEISF science
    frame. halfword_view starts at the physical record that owns the frame
    header and may include following records so science packing does not
    truncate at the record boundary.
    """
    raw, subgroups = open_vkg(path)
    for si, (hdr, body) in enumerate(subgroups):
        if not hdr.is_seisf and not hdr.label.startswith("DLT"):
            # allow if label empty but record lengths match SEISF
            if hdr.record_length not in (10752, 10764):
                continue
        rlen = hdr.record_length
        records: list[list[int]] = []
        pos = 0
        while pos + rlen <= len(body):
            records.append(body_to_halfwords(body[pos : pos + rlen]))
            pos += rlen
        for ri, hs0 in enumerate(records):
            # Extend enough for trailing-edge header BCD (year/DOY) and for
            # science packing after each discovered base.
            search_need = len(hs0) + SEISF_HEADER_HALFWORDS + 8
            hs_search = (
                list(hs0)
                if len(hs0) >= search_need
                else extend_halfwords_across_records(records, ri, search_need)
            )
            for base in find_seisf_frame_bases(
                hs_search, start_limit=len(hs0)
            ):
                need = halfwords_span_for_frame(base)
                hs = (
                    hs_search
                    if len(hs_search) >= need
                    else extend_halfwords_across_records(records, ri, need)
                )
                file_off = hdr.file_offset + 1000 + ri * rlen + base * 3
                loc = SeisfFrameLoc(si, ri, base, file_off)
                header = seisf_frame_header_bytes(hs, base)
                yield loc, hs, header


def decode_seisf_file(
    path: str,
    *,
    unscramble: bool = True,
    max_frames: Optional[int] = None,
) -> Iterator[DecodedFrame]:
    """
    Decode SEISF (vkg.1-46) frames.

    unscramble=True  -> MAP/SEISDT reconstruction then VUS science parse
    unscramble=False -> pack first 75 words as-is (debug/raw)

    Bad frames (matv out of range, short science, decode errors) yield a
    header-only DecodedFrame with note containing `/error` or `/header-only`
    rather than raising.
    """
    count = 0
    for loc, hs, header in iter_seisf_frames(path):
        year, doy = parse_seisf_header_fields(header + bytes(342))
        note = "seisf+unscr" if unscramble else "seisf-raw"
        try:
            if unscramble:
                frame = seisf_frame_to_vus_bytes(hs, loc.halfword_offset)
            else:
                frame = seisf_frame_raw_as_vus_guess(hs, loc.halfword_offset)
            dec = decode_vus_frame(frame, count)
            if dec is None:
                yield DecodedFrame(
                    count,
                    year,
                    doy,
                    [],
                    header + bytes(BYTES_PER_FRAME_VUS - 108),
                    note=note + "/header-only",
                )
            else:
                dec.frame_index = count
                dec.note = note if dec.blocks else note + "/empty-science"
                yield dec
        except Exception as exc:
            yield DecodedFrame(
                count,
                year,
                doy,
                [],
                header + bytes(BYTES_PER_FRAME_VUS - 108),
                note=f"{note}/error:{type(exc).__name__}",
            )
        count += 1
        if max_frames is not None and count >= max_frames:
            break


def describe_file(path: str) -> str:
    _, subgroups = open_vkg(path)
    lines = [f"file: {path}", f"subgroups: {len(subgroups)}"]
    for i, (h, body) in enumerate(subgroups):
        kind = "SEISF/DLT" if h.is_seisf else ("VUS" if h.is_vus else "unknown")
        nrec = len(body) // h.record_length if h.record_length else 0
        lines.append(
            f"  [{i}] label={h.label!r} file_no={h.file_no} "
            f"rec_len={h.record_length} records={nrec} kind={kind}"
        )
    return "\n".join(lines)
